# Generated by Django 4.2.16 on 2024-10-31 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_aboutpage_activitiespage_memberspage_servicespage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='banner_title',
            field=models.CharField(default='默认标题', max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='middle_title',
            field=models.CharField(default='默认中间标题', max_length=255),
        ),
    ]
