# Generated by Django 4.2.16 on 2024-11-01 11:38

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_rename_banner_title_homepage_banner_title1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='menu_items',
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
    ]
