# Generated by Django 4.2.16 on 2024-11-01 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_homepage_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='body',
        ),
    ]
