# Generated by Django 4.2.16 on 2024-11-01 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_mainmenu_remove_homepage_menu_items'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MainMenu',
        ),
    ]
