# Generated by Django 4.2.16 on 2024-11-01 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logo',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
