# Generated by Django 4.2.16 on 2024-11-02 05:11

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_alter_logo_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='group_4',
            field=wagtail.fields.StreamField([('raw_html', 0)], blank=True, block_lookup={0: ('wagtail.blocks.RawHTMLBlock', (), {})}),
        ),
    ]
