# Generated by Django 4.2.16 on 2024-11-01 12:55

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mainmenu',
            options={'verbose_name': '主导航菜单', 'verbose_name_plural': '主导航菜单'},
        ),
        migrations.AlterField(
            model_name='mainmenu',
            name='menu_items',
            field=wagtail.fields.StreamField([('menu_item', 9)], block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': '中文菜单名称'}), 1: ('wagtail.blocks.CharBlock', (), {'label': '英文菜单名称'}), 2: ('wagtail.blocks.PageChooserBlock', (), {'can_choose_root': True, 'label': '选择页面', 'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'label': '中文子菜单名称'}), 4: ('wagtail.blocks.CharBlock', (), {'label': '英文子菜单名称'}), 5: ('wagtail.blocks.PageChooserBlock', (), {'label': '选择页面', 'required': False}), 6: ('wagtail.blocks.StructBlock', [[('title_zh', 3), ('title_en', 4), ('link_page', 5)]], {}), 7: ('wagtail.blocks.ListBlock', (6,), {'label': '子菜单项', 'required': False}), 8: ('wagtail.blocks.StructBlock', [[('title_zh', 0), ('title_en', 1), ('link_page', 2), ('sub_items', 7)]], {}), 9: ('wagtail.blocks.ListBlock', (8,), {})}),
        ),
    ]
