# Generated by Django 4.2.16 on 2024-11-01 12:58

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0002_alter_mainmenu_options_alter_mainmenu_menu_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainmenu',
            name='menu_items',
            field=wagtail.fields.StreamField([('menu_item', 11)], block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': '中文菜单名称'}), 1: ('wagtail.blocks.CharBlock', (), {'label': '英文菜单名称'}), 2: ('wagtail.blocks.PageChooserBlock', (), {'can_choose_root': True, 'label': '中文页面', 'required': False}), 3: ('wagtail.blocks.PageChooserBlock', (), {'can_choose_root': True, 'label': '英文页面', 'required': False}), 4: ('wagtail.blocks.CharBlock', (), {'label': '中文子菜单名称'}), 5: ('wagtail.blocks.CharBlock', (), {'label': '英文子菜单名称'}), 6: ('wagtail.blocks.PageChooserBlock', (), {'label': '中文页面', 'required': False}), 7: ('wagtail.blocks.PageChooserBlock', (), {'label': '英文页面', 'required': False}), 8: ('wagtail.blocks.StructBlock', [[('title_zh', 4), ('title_en', 5), ('link_page_zh', 6), ('link_page_en', 7)]], {}), 9: ('wagtail.blocks.ListBlock', (8,), {'label': '子菜单项', 'required': False}), 10: ('wagtail.blocks.StructBlock', [[('title_zh', 0), ('title_en', 1), ('link_page_zh', 2), ('link_page_en', 3), ('sub_items', 9)]], {}), 11: ('wagtail.blocks.ListBlock', (10,), {})}),
        ),
    ]
